version: '3.7'

services:
  sirimulation:
    container_name: sirimulation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:8000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENV=dev
      - HOST_IP_ADDRESS=192.168.0.27